spring:
  application:
    name: SecurityTinyService
  datasource:
    url: 'jdbc:postgresql://localhost:5432/mydatabase'
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  data:
    jdbc:
      dialect: postgresql

jwt:
  secret: 'mySecretKey4554555555444447777888555566554523322'
  expiration: 10000000
remember-me:
  key: 'remember_me_key'
